describe("GLSLCSyntax", () => {
    const Namespace = require("rewire")("../dist/index.js")
    const Compile = Namespace.__get__("Compile")
    const GLSLCSyntax = Namespace.__get__("GLSLCSyntax")

    function Test(description, input, output) {
        it(description, () => {
            expect(Compile(input, GLSLCSyntax, {
                "testbvec4a": {
                    Type: "Parameter",
                    Name: "testbvec4a",
                    Primitive: "Boolean",
                    Plurality: 4
                },
                "testbvec4b": {
                    Type: "Parameter",
                    Name: "testbvec4b",
                    Primitive: "Boolean",
                    Plurality: 4
                }, "testbvec3a": {
                    Type: "Parameter",
                    Name: "testbvec3a",
                    Primitive: "Boolean",
                    Plurality: 3
                },
                "testbvec3b": {
                    Type: "Parameter",
                    Name: "testbvec3b",
                    Primitive: "Boolean",
                    Plurality: 3
                }, "testbvec2a": {
                    Type: "Parameter",
                    Name: "testbvec2a",
                    Primitive: "Boolean",
                    Plurality: 2
                },
                "testbvec2b": {
                    Type: "Parameter",
                    Name: "testbvec2b",
                    Primitive: "Boolean",
                    Plurality: 2
                }, "testboola": {
                    Type: "Parameter",
                    Name: "testboola",
                    Primitive: "Boolean",
                    Plurality: 1
                },
                "testboolb": {
                    Type: "Parameter",
                    Name: "testboolb",
                    Primitive: "Boolean",
                    Plurality: 1
                },
                "testboolc": {
                    Type: "Parameter",
                    Name: "testboolc",
                    Primitive: "Boolean",
                    Plurality: 1
                },
                "testboold": {
                    Type: "Parameter",
                    Name: "testboold",
                    Primitive: "Boolean",
                    Plurality: 1
                }
            })).toEqual(output)
        })
    }

    Test("AllBVec4", "testboola and testboolb and testboolc and testboold", "all(bvec4(testboola, testboolb, testboolc, testboold))")
    Test("AllBVec3", "testboola and testboolb and testboolc", "all(bvec3(testboola, testboolb, testboolc))")
    Test("AnyBVec4", "testboola or testboolb or testboolc or testboold", "any(bvec4(testboola, testboolb, testboolc, testboold))")
    Test("AnyBVec3", "testboola or testboolb or testboolc", "any(bvec3(testboola, testboolb, testboolc))")
    Test("AndBool", "testboola and testboolb", "(testboola && testboolb)")
    Test("AndBVec2BVec2", "testbvec2a and testbvec2b", "bvec2((testbvec2a.x && testbvec2b.x), (testbvec2a.y && testbvec2b.y))")
    Test("AndBoolBVec2", "testboola and testbvec2b", "bvec2((testboola && testbvec2b.x), (testboola && testbvec2b.y))")
    Test("AndBVec2Bool", "testbvec2a and testboolb", "bvec2((testbvec2a.x && testboolb), (testbvec2a.y && testboolb))")
    Test("AndBVec3BVec3", "testbvec3a and testbvec3b", "bvec3((testbvec3a.x && testbvec3b.x), (testbvec3a.y && testbvec3b.y), (testbvec3a.z && testbvec3b.z))")
    Test("AndBoolBVec3", "testboola and testbvec3b", "bvec3((testboola && testbvec3b.x), (testboola && testbvec3b.y), (testboola && testbvec3b.z))")
    Test("AndBVec3Bool", "testbvec3a and testboolb", "bvec3((testbvec3a.x && testboolb), (testbvec3a.y && testboolb), (testbvec3a.z && testboolb))")
    Test("AndBVec4BVec4", "testbvec4a and testbvec4b", "bvec4((testbvec4a.x && testbvec4b.x), (testbvec4a.y && testbvec4b.y), (testbvec4a.z && testbvec4b.z), (testbvec4a.w && testbvec4b.w))")
    Test("AndBoolBVec4", "testboola and testbvec4b", "bvec4((testboola && testbvec4b.x), (testboola && testbvec4b.y), (testboola && testbvec4b.z), (testboola && testbvec4b.w))")
    Test("AndBVec4Bool", "testbvec4a and testboolb", "bvec4((testbvec4a.x && testboolb), (testbvec4a.y && testboolb), (testbvec4a.z && testboolb), (testbvec4a.w && testboolb))")
    Test("OrBool", "testboola or testboolb", "(testboola || testboolb)")
    Test("OrBVec2BVec2", "testbvec2a or testbvec2b", "bvec2((testbvec2a.x || testbvec2b.x), (testbvec2a.y || testbvec2b.y))")
    Test("OrBoolBVec2", "testboola or testbvec2b", "bvec2((testboola || testbvec2b.x), (testboola || testbvec2b.y))")
    Test("OrBVec2Bool", "testbvec2a or testboolb", "bvec2((testbvec2a.x || testboolb), (testbvec2a.y || testboolb))")
    Test("OrBVec3BVec3", "testbvec3a or testbvec3b", "bvec3((testbvec3a.x || testbvec3b.x), (testbvec3a.y || testbvec3b.y), (testbvec3a.z || testbvec3b.z))")
    Test("OrBoolBVec3", "testboola or testbvec3b", "bvec3((testboola || testbvec3b.x), (testboola || testbvec3b.y), (testboola || testbvec3b.z))")
    Test("OrBVec3Bool", "testbvec3a or testboolb", "bvec3((testbvec3a.x || testboolb), (testbvec3a.y || testboolb), (testbvec3a.z || testboolb))")
    Test("OrBVec4BVec4", "testbvec4a or testbvec4b", "bvec4((testbvec4a.x || testbvec4b.x), (testbvec4a.y || testbvec4b.y), (testbvec4a.z || testbvec4b.z), (testbvec4a.w || testbvec4b.w))")
    Test("OrBoolBVec4", "testboola or testbvec4b", "bvec4((testboola || testbvec4b.x), (testboola || testbvec4b.y), (testboola || testbvec4b.z), (testboola || testbvec4b.w))")
    Test("OrBVec4Bool", "testbvec4a or testboolb", "bvec4((testbvec4a.x || testboolb), (testbvec4a.y || testboolb), (testbvec4a.z || testboolb), (testbvec4a.w || testboolb))")
    Test("NotBVec4", "(not testboola), (not testboolb), (not testboolc), (not testboold)", "not(bvec4(testboola, testboolb, testboolc, testboold))")
    Test("NotBVec3", "(not testboola), (not testboolb), (not testboolc)", "not(bvec3(testboola, testboolb, testboolc))")
    Test("NotBVec2", "(not testboola), (not testboolb)", "not(bvec2(testboola, testboolb))")
    Test("NotBool", "not testboola", "(!testboola)")
    Test("BVec4 all same", "testboola, testboola, testboola, testboola", "bvec4(testboola)")
    Test("BVec4 first different", "testboolb, testboola, testboola, testboola", "bvec4(testboolb, testboola, testboola, testboola)")
    Test("BVec4 second different", "testboola, testboolb, testboola, testboola", "bvec4(testboola, testboolb, testboola, testboola)")
    Test("BVec4 third different", "testboola, testboola, testboolb, testboola", "bvec4(testboola, testboola, testboolb, testboola)")
    Test("BVec4 fourth different", "testboola, testboola, testboola, testboolb", "bvec4(testboola, testboola, testboola, testboolb)")
    Test("BVec3 all same", "testboola, testboola, testboola", "bvec3(testboola)")
    Test("BVec3 first different", "testboolb, testboola, testboola", "bvec3(testboolb, testboola, testboola)")
    Test("BVec3 second different", "testboola, testboolb, testboola", "bvec3(testboola, testboolb, testboola)")
    Test("BVec3 third different", "testboola, testboola, testboolb", "bvec3(testboola, testboola, testboolb)")
    Test("BVec2 all same", "testboola, testboola", "bvec2(testboola)")
    Test("BVec2 first different", "testboolb, testboola", "bvec2(testboolb, testboola)")
    Test("BVec2 second different", "testboola, testboolb", "bvec2(testboola, testboolb)")
    Test("BVec4 x", "testbvec4a::0", "testbvec4a.x")
    Test("BVec4 y", "testbvec4a::1", "testbvec4a.y")
    Test("BVec4 z", "testbvec4a::2", "testbvec4a.z")
    Test("BVec4 w", "testbvec4a::3", "testbvec4a.w")
    Test("BVec4 xx", "testbvec4a::0, testbvec4a::0", "testbvec4a.xx")
    Test("BVec4 xy", "testbvec4a::0, testbvec4a::1", "testbvec4a.xy")
    Test("BVec4 xz", "testbvec4a::0, testbvec4a::2", "testbvec4a.xz")
    Test("BVec4 xw", "testbvec4a::0, testbvec4a::3", "testbvec4a.xw")
    Test("BVec4 yx", "testbvec4a::1, testbvec4a::0", "testbvec4a.yx")
    Test("BVec4 yy", "testbvec4a::1, testbvec4a::1", "testbvec4a.yy")
    Test("BVec4 yz", "testbvec4a::1, testbvec4a::2", "testbvec4a.yz")
    Test("BVec4 yw", "testbvec4a::1, testbvec4a::3", "testbvec4a.yw")
    Test("BVec4 zx", "testbvec4a::2, testbvec4a::0", "testbvec4a.zx")
    Test("BVec4 zy", "testbvec4a::2, testbvec4a::1", "testbvec4a.zy")
    Test("BVec4 zz", "testbvec4a::2, testbvec4a::2", "testbvec4a.zz")
    Test("BVec4 zw", "testbvec4a::2, testbvec4a::3", "testbvec4a.zw")
    Test("BVec4 wx", "testbvec4a::3, testbvec4a::0", "testbvec4a.wx")
    Test("BVec4 wy", "testbvec4a::3, testbvec4a::1", "testbvec4a.wy")
    Test("BVec4 wz", "testbvec4a::3, testbvec4a::2", "testbvec4a.wz")
    Test("BVec4 ww", "testbvec4a::3, testbvec4a::3", "testbvec4a.ww")
    Test("BVec4 xxx", "testbvec4a::0, testbvec4a::0, testbvec4a::0", "testbvec4a.xxx")
    Test("BVec4 xxy", "testbvec4a::0, testbvec4a::0, testbvec4a::1", "testbvec4a.xxy")
    Test("BVec4 xxz", "testbvec4a::0, testbvec4a::0, testbvec4a::2", "testbvec4a.xxz")
    Test("BVec4 xxw", "testbvec4a::0, testbvec4a::0, testbvec4a::3", "testbvec4a.xxw")
    Test("BVec4 xyx", "testbvec4a::0, testbvec4a::1, testbvec4a::0", "testbvec4a.xyx")
    Test("BVec4 xyy", "testbvec4a::0, testbvec4a::1, testbvec4a::1", "testbvec4a.xyy")
    Test("BVec4 xyz", "testbvec4a::0, testbvec4a::1, testbvec4a::2", "testbvec4a.xyz")
    Test("BVec4 xyw", "testbvec4a::0, testbvec4a::1, testbvec4a::3", "testbvec4a.xyw")
    Test("BVec4 xzx", "testbvec4a::0, testbvec4a::2, testbvec4a::0", "testbvec4a.xzx")
    Test("BVec4 xzy", "testbvec4a::0, testbvec4a::2, testbvec4a::1", "testbvec4a.xzy")
    Test("BVec4 xzz", "testbvec4a::0, testbvec4a::2, testbvec4a::2", "testbvec4a.xzz")
    Test("BVec4 xzw", "testbvec4a::0, testbvec4a::2, testbvec4a::3", "testbvec4a.xzw")
    Test("BVec4 xwx", "testbvec4a::0, testbvec4a::3, testbvec4a::0", "testbvec4a.xwx")
    Test("BVec4 xwy", "testbvec4a::0, testbvec4a::3, testbvec4a::1", "testbvec4a.xwy")
    Test("BVec4 xwz", "testbvec4a::0, testbvec4a::3, testbvec4a::2", "testbvec4a.xwz")
    Test("BVec4 xww", "testbvec4a::0, testbvec4a::3, testbvec4a::3", "testbvec4a.xww")
    Test("BVec4 yxx", "testbvec4a::1, testbvec4a::0, testbvec4a::0", "testbvec4a.yxx")
    Test("BVec4 yxy", "testbvec4a::1, testbvec4a::0, testbvec4a::1", "testbvec4a.yxy")
    Test("BVec4 yxz", "testbvec4a::1, testbvec4a::0, testbvec4a::2", "testbvec4a.yxz")
    Test("BVec4 yxw", "testbvec4a::1, testbvec4a::0, testbvec4a::3", "testbvec4a.yxw")
    Test("BVec4 yyx", "testbvec4a::1, testbvec4a::1, testbvec4a::0", "testbvec4a.yyx")
    Test("BVec4 yyy", "testbvec4a::1, testbvec4a::1, testbvec4a::1", "testbvec4a.yyy")
    Test("BVec4 yyz", "testbvec4a::1, testbvec4a::1, testbvec4a::2", "testbvec4a.yyz")
    Test("BVec4 yyw", "testbvec4a::1, testbvec4a::1, testbvec4a::3", "testbvec4a.yyw")
    Test("BVec4 yzx", "testbvec4a::1, testbvec4a::2, testbvec4a::0", "testbvec4a.yzx")
    Test("BVec4 yzy", "testbvec4a::1, testbvec4a::2, testbvec4a::1", "testbvec4a.yzy")
    Test("BVec4 yzz", "testbvec4a::1, testbvec4a::2, testbvec4a::2", "testbvec4a.yzz")
    Test("BVec4 yzw", "testbvec4a::1, testbvec4a::2, testbvec4a::3", "testbvec4a.yzw")
    Test("BVec4 ywx", "testbvec4a::1, testbvec4a::3, testbvec4a::0", "testbvec4a.ywx")
    Test("BVec4 ywy", "testbvec4a::1, testbvec4a::3, testbvec4a::1", "testbvec4a.ywy")
    Test("BVec4 ywz", "testbvec4a::1, testbvec4a::3, testbvec4a::2", "testbvec4a.ywz")
    Test("BVec4 yww", "testbvec4a::1, testbvec4a::3, testbvec4a::3", "testbvec4a.yww")
    Test("BVec4 zxx", "testbvec4a::2, testbvec4a::0, testbvec4a::0", "testbvec4a.zxx")
    Test("BVec4 zxy", "testbvec4a::2, testbvec4a::0, testbvec4a::1", "testbvec4a.zxy")
    Test("BVec4 zxz", "testbvec4a::2, testbvec4a::0, testbvec4a::2", "testbvec4a.zxz")
    Test("BVec4 zxw", "testbvec4a::2, testbvec4a::0, testbvec4a::3", "testbvec4a.zxw")
    Test("BVec4 zyx", "testbvec4a::2, testbvec4a::1, testbvec4a::0", "testbvec4a.zyx")
    Test("BVec4 zyy", "testbvec4a::2, testbvec4a::1, testbvec4a::1", "testbvec4a.zyy")
    Test("BVec4 zyz", "testbvec4a::2, testbvec4a::1, testbvec4a::2", "testbvec4a.zyz")
    Test("BVec4 zyw", "testbvec4a::2, testbvec4a::1, testbvec4a::3", "testbvec4a.zyw")
    Test("BVec4 zzx", "testbvec4a::2, testbvec4a::2, testbvec4a::0", "testbvec4a.zzx")
    Test("BVec4 zzy", "testbvec4a::2, testbvec4a::2, testbvec4a::1", "testbvec4a.zzy")
    Test("BVec4 zzz", "testbvec4a::2, testbvec4a::2, testbvec4a::2", "testbvec4a.zzz")
    Test("BVec4 zzw", "testbvec4a::2, testbvec4a::2, testbvec4a::3", "testbvec4a.zzw")
    Test("BVec4 zwx", "testbvec4a::2, testbvec4a::3, testbvec4a::0", "testbvec4a.zwx")
    Test("BVec4 zwy", "testbvec4a::2, testbvec4a::3, testbvec4a::1", "testbvec4a.zwy")
    Test("BVec4 zwz", "testbvec4a::2, testbvec4a::3, testbvec4a::2", "testbvec4a.zwz")
    Test("BVec4 zww", "testbvec4a::2, testbvec4a::3, testbvec4a::3", "testbvec4a.zww")
    Test("BVec4 wxx", "testbvec4a::3, testbvec4a::0, testbvec4a::0", "testbvec4a.wxx")
    Test("BVec4 wxy", "testbvec4a::3, testbvec4a::0, testbvec4a::1", "testbvec4a.wxy")
    Test("BVec4 wxz", "testbvec4a::3, testbvec4a::0, testbvec4a::2", "testbvec4a.wxz")
    Test("BVec4 wxw", "testbvec4a::3, testbvec4a::0, testbvec4a::3", "testbvec4a.wxw")
    Test("BVec4 wyx", "testbvec4a::3, testbvec4a::1, testbvec4a::0", "testbvec4a.wyx")
    Test("BVec4 wyy", "testbvec4a::3, testbvec4a::1, testbvec4a::1", "testbvec4a.wyy")
    Test("BVec4 wyz", "testbvec4a::3, testbvec4a::1, testbvec4a::2", "testbvec4a.wyz")
    Test("BVec4 wyw", "testbvec4a::3, testbvec4a::1, testbvec4a::3", "testbvec4a.wyw")
    Test("BVec4 wzx", "testbvec4a::3, testbvec4a::2, testbvec4a::0", "testbvec4a.wzx")
    Test("BVec4 wzy", "testbvec4a::3, testbvec4a::2, testbvec4a::1", "testbvec4a.wzy")
    Test("BVec4 wzz", "testbvec4a::3, testbvec4a::2, testbvec4a::2", "testbvec4a.wzz")
    Test("BVec4 wzw", "testbvec4a::3, testbvec4a::2, testbvec4a::3", "testbvec4a.wzw")
    Test("BVec4 wwx", "testbvec4a::3, testbvec4a::3, testbvec4a::0", "testbvec4a.wwx")
    Test("BVec4 wwy", "testbvec4a::3, testbvec4a::3, testbvec4a::1", "testbvec4a.wwy")
    Test("BVec4 wwz", "testbvec4a::3, testbvec4a::3, testbvec4a::2", "testbvec4a.wwz")
    Test("BVec4 www", "testbvec4a::3, testbvec4a::3, testbvec4a::3", "testbvec4a.www")
    Test("BVec4 xxxx", "testbvec4a::0, testbvec4a::0, testbvec4a::0, testbvec4a::0", "testbvec4a.xxxx")
    Test("BVec4 xxxy", "testbvec4a::0, testbvec4a::0, testbvec4a::0, testbvec4a::1", "testbvec4a.xxxy")
    Test("BVec4 xxxz", "testbvec4a::0, testbvec4a::0, testbvec4a::0, testbvec4a::2", "testbvec4a.xxxz")
    Test("BVec4 xxxw", "testbvec4a::0, testbvec4a::0, testbvec4a::0, testbvec4a::3", "testbvec4a.xxxw")
    Test("BVec4 xxyx", "testbvec4a::0, testbvec4a::0, testbvec4a::1, testbvec4a::0", "testbvec4a.xxyx")
    Test("BVec4 xxyy", "testbvec4a::0, testbvec4a::0, testbvec4a::1, testbvec4a::1", "testbvec4a.xxyy")
    Test("BVec4 xxyz", "testbvec4a::0, testbvec4a::0, testbvec4a::1, testbvec4a::2", "testbvec4a.xxyz")
    Test("BVec4 xxyw", "testbvec4a::0, testbvec4a::0, testbvec4a::1, testbvec4a::3", "testbvec4a.xxyw")
    Test("BVec4 xxzx", "testbvec4a::0, testbvec4a::0, testbvec4a::2, testbvec4a::0", "testbvec4a.xxzx")
    Test("BVec4 xxzy", "testbvec4a::0, testbvec4a::0, testbvec4a::2, testbvec4a::1", "testbvec4a.xxzy")
    Test("BVec4 xxzz", "testbvec4a::0, testbvec4a::0, testbvec4a::2, testbvec4a::2", "testbvec4a.xxzz")
    Test("BVec4 xxzw", "testbvec4a::0, testbvec4a::0, testbvec4a::2, testbvec4a::3", "testbvec4a.xxzw")
    Test("BVec4 xxwx", "testbvec4a::0, testbvec4a::0, testbvec4a::3, testbvec4a::0", "testbvec4a.xxwx")
    Test("BVec4 xxwy", "testbvec4a::0, testbvec4a::0, testbvec4a::3, testbvec4a::1", "testbvec4a.xxwy")
    Test("BVec4 xxwz", "testbvec4a::0, testbvec4a::0, testbvec4a::3, testbvec4a::2", "testbvec4a.xxwz")
    Test("BVec4 xxww", "testbvec4a::0, testbvec4a::0, testbvec4a::3, testbvec4a::3", "testbvec4a.xxww")
    Test("BVec4 xyxx", "testbvec4a::0, testbvec4a::1, testbvec4a::0, testbvec4a::0", "testbvec4a.xyxx")
    Test("BVec4 xyxy", "testbvec4a::0, testbvec4a::1, testbvec4a::0, testbvec4a::1", "testbvec4a.xyxy")
    Test("BVec4 xyxz", "testbvec4a::0, testbvec4a::1, testbvec4a::0, testbvec4a::2", "testbvec4a.xyxz")
    Test("BVec4 xyxw", "testbvec4a::0, testbvec4a::1, testbvec4a::0, testbvec4a::3", "testbvec4a.xyxw")
    Test("BVec4 xyyx", "testbvec4a::0, testbvec4a::1, testbvec4a::1, testbvec4a::0", "testbvec4a.xyyx")
    Test("BVec4 xyyy", "testbvec4a::0, testbvec4a::1, testbvec4a::1, testbvec4a::1", "testbvec4a.xyyy")
    Test("BVec4 xyyz", "testbvec4a::0, testbvec4a::1, testbvec4a::1, testbvec4a::2", "testbvec4a.xyyz")
    Test("BVec4 xyyw", "testbvec4a::0, testbvec4a::1, testbvec4a::1, testbvec4a::3", "testbvec4a.xyyw")
    Test("BVec4 xyzx", "testbvec4a::0, testbvec4a::1, testbvec4a::2, testbvec4a::0", "testbvec4a.xyzx")
    Test("BVec4 xyzy", "testbvec4a::0, testbvec4a::1, testbvec4a::2, testbvec4a::1", "testbvec4a.xyzy")
    Test("BVec4 xyzz", "testbvec4a::0, testbvec4a::1, testbvec4a::2, testbvec4a::2", "testbvec4a.xyzz")
    Test("BVec4 xyzw", "testbvec4a::0, testbvec4a::1, testbvec4a::2, testbvec4a::3", "testbvec4a")
    Test("BVec4 xywy", "testbvec4a::0, testbvec4a::1, testbvec4a::3, testbvec4a::1", "testbvec4a.xywy")
    Test("BVec4 xywx", "testbvec4a::0, testbvec4a::1, testbvec4a::3, testbvec4a::0", "testbvec4a.xywx")
    Test("BVec4 xyww", "testbvec4a::0, testbvec4a::1, testbvec4a::3, testbvec4a::3", "testbvec4a.xyww")
    Test("BVec4 xywz", "testbvec4a::0, testbvec4a::1, testbvec4a::3, testbvec4a::2", "testbvec4a.xywz")
    Test("BVec4 xzxy", "testbvec4a::0, testbvec4a::2, testbvec4a::0, testbvec4a::1", "testbvec4a.xzxy")
    Test("BVec4 xzxx", "testbvec4a::0, testbvec4a::2, testbvec4a::0, testbvec4a::0", "testbvec4a.xzxx")
    Test("BVec4 xzxw", "testbvec4a::0, testbvec4a::2, testbvec4a::0, testbvec4a::3", "testbvec4a.xzxw")
    Test("BVec4 xzxz", "testbvec4a::0, testbvec4a::2, testbvec4a::0, testbvec4a::2", "testbvec4a.xzxz")
    Test("BVec4 xzyy", "testbvec4a::0, testbvec4a::2, testbvec4a::1, testbvec4a::1", "testbvec4a.xzyy")
    Test("BVec4 xzyx", "testbvec4a::0, testbvec4a::2, testbvec4a::1, testbvec4a::0", "testbvec4a.xzyx")
    Test("BVec4 xzyw", "testbvec4a::0, testbvec4a::2, testbvec4a::1, testbvec4a::3", "testbvec4a.xzyw")
    Test("BVec4 xzyz", "testbvec4a::0, testbvec4a::2, testbvec4a::1, testbvec4a::2", "testbvec4a.xzyz")
    Test("BVec4 xzzy", "testbvec4a::0, testbvec4a::2, testbvec4a::2, testbvec4a::1", "testbvec4a.xzzy")
    Test("BVec4 xzzx", "testbvec4a::0, testbvec4a::2, testbvec4a::2, testbvec4a::0", "testbvec4a.xzzx")
    Test("BVec4 xzzw", "testbvec4a::0, testbvec4a::2, testbvec4a::2, testbvec4a::3", "testbvec4a.xzzw")
    Test("BVec4 xzzz", "testbvec4a::0, testbvec4a::2, testbvec4a::2, testbvec4a::2", "testbvec4a.xzzz")
    Test("BVec4 xzwy", "testbvec4a::0, testbvec4a::2, testbvec4a::3, testbvec4a::1", "testbvec4a.xzwy")
    Test("BVec4 xzwx", "testbvec4a::0, testbvec4a::2, testbvec4a::3, testbvec4a::0", "testbvec4a.xzwx")
    Test("BVec4 xzww", "testbvec4a::0, testbvec4a::2, testbvec4a::3, testbvec4a::3", "testbvec4a.xzww")
    Test("BVec4 xzwz", "testbvec4a::0, testbvec4a::2, testbvec4a::3, testbvec4a::2", "testbvec4a.xzwz")
    Test("BVec4 xwxy", "testbvec4a::0, testbvec4a::3, testbvec4a::0, testbvec4a::1", "testbvec4a.xwxy")
    Test("BVec4 xwxx", "testbvec4a::0, testbvec4a::3, testbvec4a::0, testbvec4a::0", "testbvec4a.xwxx")
    Test("BVec4 xwxw", "testbvec4a::0, testbvec4a::3, testbvec4a::0, testbvec4a::3", "testbvec4a.xwxw")
    Test("BVec4 xwxz", "testbvec4a::0, testbvec4a::3, testbvec4a::0, testbvec4a::2", "testbvec4a.xwxz")
    Test("BVec4 xwyy", "testbvec4a::0, testbvec4a::3, testbvec4a::1, testbvec4a::1", "testbvec4a.xwyy")
    Test("BVec4 xwyx", "testbvec4a::0, testbvec4a::3, testbvec4a::1, testbvec4a::0", "testbvec4a.xwyx")
    Test("BVec4 xwyw", "testbvec4a::0, testbvec4a::3, testbvec4a::1, testbvec4a::3", "testbvec4a.xwyw")
    Test("BVec4 xwyz", "testbvec4a::0, testbvec4a::3, testbvec4a::1, testbvec4a::2", "testbvec4a.xwyz")
    Test("BVec4 xwzy", "testbvec4a::0, testbvec4a::3, testbvec4a::2, testbvec4a::1", "testbvec4a.xwzy")
    Test("BVec4 xwzx", "testbvec4a::0, testbvec4a::3, testbvec4a::2, testbvec4a::0", "testbvec4a.xwzx")
    Test("BVec4 xwzw", "testbvec4a::0, testbvec4a::3, testbvec4a::2, testbvec4a::3", "testbvec4a.xwzw")
    Test("BVec4 xwzz", "testbvec4a::0, testbvec4a::3, testbvec4a::2, testbvec4a::2", "testbvec4a.xwzz")
    Test("BVec4 xwwy", "testbvec4a::0, testbvec4a::3, testbvec4a::3, testbvec4a::1", "testbvec4a.xwwy")
    Test("BVec4 xwwx", "testbvec4a::0, testbvec4a::3, testbvec4a::3, testbvec4a::0", "testbvec4a.xwwx")
    Test("BVec4 xwww", "testbvec4a::0, testbvec4a::3, testbvec4a::3, testbvec4a::3", "testbvec4a.xwww")
    Test("BVec4 xwwz", "testbvec4a::0, testbvec4a::3, testbvec4a::3, testbvec4a::2", "testbvec4a.xwwz")
    Test("BVec4 yxxx", "testbvec4a::1, testbvec4a::0, testbvec4a::0, testbvec4a::0", "testbvec4a.yxxx")
    Test("BVec4 yxxy", "testbvec4a::1, testbvec4a::0, testbvec4a::0, testbvec4a::1", "testbvec4a.yxxy")
    Test("BVec4 yxxz", "testbvec4a::1, testbvec4a::0, testbvec4a::0, testbvec4a::2", "testbvec4a.yxxz")
    Test("BVec4 yxxw", "testbvec4a::1, testbvec4a::0, testbvec4a::0, testbvec4a::3", "testbvec4a.yxxw")
    Test("BVec4 yxyx", "testbvec4a::1, testbvec4a::0, testbvec4a::1, testbvec4a::0", "testbvec4a.yxyx")
    Test("BVec4 yxyy", "testbvec4a::1, testbvec4a::0, testbvec4a::1, testbvec4a::1", "testbvec4a.yxyy")
    Test("BVec4 yxyz", "testbvec4a::1, testbvec4a::0, testbvec4a::1, testbvec4a::2", "testbvec4a.yxyz")
    Test("BVec4 yxyw", "testbvec4a::1, testbvec4a::0, testbvec4a::1, testbvec4a::3", "testbvec4a.yxyw")
    Test("BVec4 yxzx", "testbvec4a::1, testbvec4a::0, testbvec4a::2, testbvec4a::0", "testbvec4a.yxzx")
    Test("BVec4 yxzy", "testbvec4a::1, testbvec4a::0, testbvec4a::2, testbvec4a::1", "testbvec4a.yxzy")
    Test("BVec4 yxzz", "testbvec4a::1, testbvec4a::0, testbvec4a::2, testbvec4a::2", "testbvec4a.yxzz")
    Test("BVec4 yxzw", "testbvec4a::1, testbvec4a::0, testbvec4a::2, testbvec4a::3", "testbvec4a.yxzw")
    Test("BVec4 yxwx", "testbvec4a::1, testbvec4a::0, testbvec4a::3, testbvec4a::0", "testbvec4a.yxwx")
    Test("BVec4 yxwy", "testbvec4a::1, testbvec4a::0, testbvec4a::3, testbvec4a::1", "testbvec4a.yxwy")
    Test("BVec4 yxwz", "testbvec4a::1, testbvec4a::0, testbvec4a::3, testbvec4a::2", "testbvec4a.yxwz")
    Test("BVec4 yxww", "testbvec4a::1, testbvec4a::0, testbvec4a::3, testbvec4a::3", "testbvec4a.yxww")
    Test("BVec4 yyxx", "testbvec4a::1, testbvec4a::1, testbvec4a::0, testbvec4a::0", "testbvec4a.yyxx")
    Test("BVec4 yyxy", "testbvec4a::1, testbvec4a::1, testbvec4a::0, testbvec4a::1", "testbvec4a.yyxy")
    Test("BVec4 yyxz", "testbvec4a::1, testbvec4a::1, testbvec4a::0, testbvec4a::2", "testbvec4a.yyxz")
    Test("BVec4 yyxw", "testbvec4a::1, testbvec4a::1, testbvec4a::0, testbvec4a::3", "testbvec4a.yyxw")
    Test("BVec4 yyyx", "testbvec4a::1, testbvec4a::1, testbvec4a::1, testbvec4a::0", "testbvec4a.yyyx")
    Test("BVec4 yyyy", "testbvec4a::1, testbvec4a::1, testbvec4a::1, testbvec4a::1", "testbvec4a.yyyy")
    Test("BVec4 yyyz", "testbvec4a::1, testbvec4a::1, testbvec4a::1, testbvec4a::2", "testbvec4a.yyyz")
    Test("BVec4 yyyw", "testbvec4a::1, testbvec4a::1, testbvec4a::1, testbvec4a::3", "testbvec4a.yyyw")
    Test("BVec4 yyzx", "testbvec4a::1, testbvec4a::1, testbvec4a::2, testbvec4a::0", "testbvec4a.yyzx")
    Test("BVec4 yyzy", "testbvec4a::1, testbvec4a::1, testbvec4a::2, testbvec4a::1", "testbvec4a.yyzy")
    Test("BVec4 yyzz", "testbvec4a::1, testbvec4a::1, testbvec4a::2, testbvec4a::2", "testbvec4a.yyzz")
    Test("BVec4 yyzw", "testbvec4a::1, testbvec4a::1, testbvec4a::2, testbvec4a::3", "testbvec4a.yyzw")
    Test("BVec4 yywy", "testbvec4a::1, testbvec4a::1, testbvec4a::3, testbvec4a::1", "testbvec4a.yywy")
    Test("BVec4 yywx", "testbvec4a::1, testbvec4a::1, testbvec4a::3, testbvec4a::0", "testbvec4a.yywx")
    Test("BVec4 yyww", "testbvec4a::1, testbvec4a::1, testbvec4a::3, testbvec4a::3", "testbvec4a.yyww")
    Test("BVec4 yywz", "testbvec4a::1, testbvec4a::1, testbvec4a::3, testbvec4a::2", "testbvec4a.yywz")
    Test("BVec4 yzxy", "testbvec4a::1, testbvec4a::2, testbvec4a::0, testbvec4a::1", "testbvec4a.yzxy")
    Test("BVec4 yzxx", "testbvec4a::1, testbvec4a::2, testbvec4a::0, testbvec4a::0", "testbvec4a.yzxx")
    Test("BVec4 yzxw", "testbvec4a::1, testbvec4a::2, testbvec4a::0, testbvec4a::3", "testbvec4a.yzxw")
    Test("BVec4 yzxz", "testbvec4a::1, testbvec4a::2, testbvec4a::0, testbvec4a::2", "testbvec4a.yzxz")
    Test("BVec4 yzyy", "testbvec4a::1, testbvec4a::2, testbvec4a::1, testbvec4a::1", "testbvec4a.yzyy")
    Test("BVec4 yzyx", "testbvec4a::1, testbvec4a::2, testbvec4a::1, testbvec4a::0", "testbvec4a.yzyx")
    Test("BVec4 yzyw", "testbvec4a::1, testbvec4a::2, testbvec4a::1, testbvec4a::3", "testbvec4a.yzyw")
    Test("BVec4 yzyz", "testbvec4a::1, testbvec4a::2, testbvec4a::1, testbvec4a::2", "testbvec4a.yzyz")
    Test("BVec4 yzzy", "testbvec4a::1, testbvec4a::2, testbvec4a::2, testbvec4a::1", "testbvec4a.yzzy")
    Test("BVec4 yzzx", "testbvec4a::1, testbvec4a::2, testbvec4a::2, testbvec4a::0", "testbvec4a.yzzx")
    Test("BVec4 yzzw", "testbvec4a::1, testbvec4a::2, testbvec4a::2, testbvec4a::3", "testbvec4a.yzzw")
    Test("BVec4 yzzz", "testbvec4a::1, testbvec4a::2, testbvec4a::2, testbvec4a::2", "testbvec4a.yzzz")
    Test("BVec4 yzwy", "testbvec4a::1, testbvec4a::2, testbvec4a::3, testbvec4a::1", "testbvec4a.yzwy")
    Test("BVec4 yzwx", "testbvec4a::1, testbvec4a::2, testbvec4a::3, testbvec4a::0", "testbvec4a.yzwx")
    Test("BVec4 yzww", "testbvec4a::1, testbvec4a::2, testbvec4a::3, testbvec4a::3", "testbvec4a.yzww")
    Test("BVec4 yzwz", "testbvec4a::1, testbvec4a::2, testbvec4a::3, testbvec4a::2", "testbvec4a.yzwz")
    Test("BVec4 ywxy", "testbvec4a::1, testbvec4a::3, testbvec4a::0, testbvec4a::1", "testbvec4a.ywxy")
    Test("BVec4 ywxx", "testbvec4a::1, testbvec4a::3, testbvec4a::0, testbvec4a::0", "testbvec4a.ywxx")
    Test("BVec4 ywxw", "testbvec4a::1, testbvec4a::3, testbvec4a::0, testbvec4a::3", "testbvec4a.ywxw")
    Test("BVec4 ywxz", "testbvec4a::1, testbvec4a::3, testbvec4a::0, testbvec4a::2", "testbvec4a.ywxz")
    Test("BVec4 ywyy", "testbvec4a::1, testbvec4a::3, testbvec4a::1, testbvec4a::1", "testbvec4a.ywyy")
    Test("BVec4 ywyx", "testbvec4a::1, testbvec4a::3, testbvec4a::1, testbvec4a::0", "testbvec4a.ywyx")
    Test("BVec4 ywyw", "testbvec4a::1, testbvec4a::3, testbvec4a::1, testbvec4a::3", "testbvec4a.ywyw")
    Test("BVec4 ywyz", "testbvec4a::1, testbvec4a::3, testbvec4a::1, testbvec4a::2", "testbvec4a.ywyz")
    Test("BVec4 ywzy", "testbvec4a::1, testbvec4a::3, testbvec4a::2, testbvec4a::1", "testbvec4a.ywzy")
    Test("BVec4 ywzx", "testbvec4a::1, testbvec4a::3, testbvec4a::2, testbvec4a::0", "testbvec4a.ywzx")
    Test("BVec4 ywzw", "testbvec4a::1, testbvec4a::3, testbvec4a::2, testbvec4a::3", "testbvec4a.ywzw")
    Test("BVec4 ywzz", "testbvec4a::1, testbvec4a::3, testbvec4a::2, testbvec4a::2", "testbvec4a.ywzz")
    Test("BVec4 ywwy", "testbvec4a::1, testbvec4a::3, testbvec4a::3, testbvec4a::1", "testbvec4a.ywwy")
    Test("BVec4 ywwx", "testbvec4a::1, testbvec4a::3, testbvec4a::3, testbvec4a::0", "testbvec4a.ywwx")
    Test("BVec4 ywww", "testbvec4a::1, testbvec4a::3, testbvec4a::3, testbvec4a::3", "testbvec4a.ywww")
    Test("BVec4 ywwz", "testbvec4a::1, testbvec4a::3, testbvec4a::3, testbvec4a::2", "testbvec4a.ywwz")
    Test("BVec4 zxxx", "testbvec4a::2, testbvec4a::0, testbvec4a::0, testbvec4a::0", "testbvec4a.zxxx")
    Test("BVec4 zxxy", "testbvec4a::2, testbvec4a::0, testbvec4a::0, testbvec4a::1", "testbvec4a.zxxy")
    Test("BVec4 zxxz", "testbvec4a::2, testbvec4a::0, testbvec4a::0, testbvec4a::2", "testbvec4a.zxxz")
    Test("BVec4 zxxw", "testbvec4a::2, testbvec4a::0, testbvec4a::0, testbvec4a::3", "testbvec4a.zxxw")
    Test("BVec4 zxyx", "testbvec4a::2, testbvec4a::0, testbvec4a::1, testbvec4a::0", "testbvec4a.zxyx")
    Test("BVec4 zxyy", "testbvec4a::2, testbvec4a::0, testbvec4a::1, testbvec4a::1", "testbvec4a.zxyy")
    Test("BVec4 zxyz", "testbvec4a::2, testbvec4a::0, testbvec4a::1, testbvec4a::2", "testbvec4a.zxyz")
    Test("BVec4 zxyw", "testbvec4a::2, testbvec4a::0, testbvec4a::1, testbvec4a::3", "testbvec4a.zxyw")
    Test("BVec4 zxzx", "testbvec4a::2, testbvec4a::0, testbvec4a::2, testbvec4a::0", "testbvec4a.zxzx")
    Test("BVec4 zxzy", "testbvec4a::2, testbvec4a::0, testbvec4a::2, testbvec4a::1", "testbvec4a.zxzy")
    Test("BVec4 zxzz", "testbvec4a::2, testbvec4a::0, testbvec4a::2, testbvec4a::2", "testbvec4a.zxzz")
    Test("BVec4 zxzw", "testbvec4a::2, testbvec4a::0, testbvec4a::2, testbvec4a::3", "testbvec4a.zxzw")
    Test("BVec4 zxwx", "testbvec4a::2, testbvec4a::0, testbvec4a::3, testbvec4a::0", "testbvec4a.zxwx")
    Test("BVec4 zxwy", "testbvec4a::2, testbvec4a::0, testbvec4a::3, testbvec4a::1", "testbvec4a.zxwy")
    Test("BVec4 zxwz", "testbvec4a::2, testbvec4a::0, testbvec4a::3, testbvec4a::2", "testbvec4a.zxwz")
    Test("BVec4 zxww", "testbvec4a::2, testbvec4a::0, testbvec4a::3, testbvec4a::3", "testbvec4a.zxww")
    Test("BVec4 zyxx", "testbvec4a::2, testbvec4a::1, testbvec4a::0, testbvec4a::0", "testbvec4a.zyxx")
    Test("BVec4 zyxy", "testbvec4a::2, testbvec4a::1, testbvec4a::0, testbvec4a::1", "testbvec4a.zyxy")
    Test("BVec4 zyxz", "testbvec4a::2, testbvec4a::1, testbvec4a::0, testbvec4a::2", "testbvec4a.zyxz")
    Test("BVec4 zyxw", "testbvec4a::2, testbvec4a::1, testbvec4a::0, testbvec4a::3", "testbvec4a.zyxw")
    Test("BVec4 zyyx", "testbvec4a::2, testbvec4a::1, testbvec4a::1, testbvec4a::0", "testbvec4a.zyyx")
    Test("BVec4 zyyy", "testbvec4a::2, testbvec4a::1, testbvec4a::1, testbvec4a::1", "testbvec4a.zyyy")
    Test("BVec4 zyyz", "testbvec4a::2, testbvec4a::1, testbvec4a::1, testbvec4a::2", "testbvec4a.zyyz")
    Test("BVec4 zyyw", "testbvec4a::2, testbvec4a::1, testbvec4a::1, testbvec4a::3", "testbvec4a.zyyw")
    Test("BVec4 zyzx", "testbvec4a::2, testbvec4a::1, testbvec4a::2, testbvec4a::0", "testbvec4a.zyzx")
    Test("BVec4 zyzy", "testbvec4a::2, testbvec4a::1, testbvec4a::2, testbvec4a::1", "testbvec4a.zyzy")
    Test("BVec4 zyzz", "testbvec4a::2, testbvec4a::1, testbvec4a::2, testbvec4a::2", "testbvec4a.zyzz")
    Test("BVec4 zyzw", "testbvec4a::2, testbvec4a::1, testbvec4a::2, testbvec4a::3", "testbvec4a.zyzw")
    Test("BVec4 zywy", "testbvec4a::2, testbvec4a::1, testbvec4a::3, testbvec4a::1", "testbvec4a.zywy")
    Test("BVec4 zywx", "testbvec4a::2, testbvec4a::1, testbvec4a::3, testbvec4a::0", "testbvec4a.zywx")
    Test("BVec4 zyww", "testbvec4a::2, testbvec4a::1, testbvec4a::3, testbvec4a::3", "testbvec4a.zyww")
    Test("BVec4 zywz", "testbvec4a::2, testbvec4a::1, testbvec4a::3, testbvec4a::2", "testbvec4a.zywz")
    Test("BVec4 zzxy", "testbvec4a::2, testbvec4a::2, testbvec4a::0, testbvec4a::1", "testbvec4a.zzxy")
    Test("BVec4 zzxx", "testbvec4a::2, testbvec4a::2, testbvec4a::0, testbvec4a::0", "testbvec4a.zzxx")
    Test("BVec4 zzxw", "testbvec4a::2, testbvec4a::2, testbvec4a::0, testbvec4a::3", "testbvec4a.zzxw")
    Test("BVec4 zzxz", "testbvec4a::2, testbvec4a::2, testbvec4a::0, testbvec4a::2", "testbvec4a.zzxz")
    Test("BVec4 zzyy", "testbvec4a::2, testbvec4a::2, testbvec4a::1, testbvec4a::1", "testbvec4a.zzyy")
    Test("BVec4 zzyx", "testbvec4a::2, testbvec4a::2, testbvec4a::1, testbvec4a::0", "testbvec4a.zzyx")
    Test("BVec4 zzyw", "testbvec4a::2, testbvec4a::2, testbvec4a::1, testbvec4a::3", "testbvec4a.zzyw")
    Test("BVec4 zzyz", "testbvec4a::2, testbvec4a::2, testbvec4a::1, testbvec4a::2", "testbvec4a.zzyz")
    Test("BVec4 zzzy", "testbvec4a::2, testbvec4a::2, testbvec4a::2, testbvec4a::1", "testbvec4a.zzzy")
    Test("BVec4 zzzx", "testbvec4a::2, testbvec4a::2, testbvec4a::2, testbvec4a::0", "testbvec4a.zzzx")
    Test("BVec4 zzzw", "testbvec4a::2, testbvec4a::2, testbvec4a::2, testbvec4a::3", "testbvec4a.zzzw")
    Test("BVec4 zzzz", "testbvec4a::2, testbvec4a::2, testbvec4a::2, testbvec4a::2", "testbvec4a.zzzz")
    Test("BVec4 zzwy", "testbvec4a::2, testbvec4a::2, testbvec4a::3, testbvec4a::1", "testbvec4a.zzwy")
    Test("BVec4 zzwx", "testbvec4a::2, testbvec4a::2, testbvec4a::3, testbvec4a::0", "testbvec4a.zzwx")
    Test("BVec4 zzww", "testbvec4a::2, testbvec4a::2, testbvec4a::3, testbvec4a::3", "testbvec4a.zzww")
    Test("BVec4 zzwz", "testbvec4a::2, testbvec4a::2, testbvec4a::3, testbvec4a::2", "testbvec4a.zzwz")
    Test("BVec4 zwxy", "testbvec4a::2, testbvec4a::3, testbvec4a::0, testbvec4a::1", "testbvec4a.zwxy")
    Test("BVec4 zwxx", "testbvec4a::2, testbvec4a::3, testbvec4a::0, testbvec4a::0", "testbvec4a.zwxx")
    Test("BVec4 zwxw", "testbvec4a::2, testbvec4a::3, testbvec4a::0, testbvec4a::3", "testbvec4a.zwxw")
    Test("BVec4 zwxz", "testbvec4a::2, testbvec4a::3, testbvec4a::0, testbvec4a::2", "testbvec4a.zwxz")
    Test("BVec4 zwyy", "testbvec4a::2, testbvec4a::3, testbvec4a::1, testbvec4a::1", "testbvec4a.zwyy")
    Test("BVec4 zwyx", "testbvec4a::2, testbvec4a::3, testbvec4a::1, testbvec4a::0", "testbvec4a.zwyx")
    Test("BVec4 zwyw", "testbvec4a::2, testbvec4a::3, testbvec4a::1, testbvec4a::3", "testbvec4a.zwyw")
    Test("BVec4 zwyz", "testbvec4a::2, testbvec4a::3, testbvec4a::1, testbvec4a::2", "testbvec4a.zwyz")
    Test("BVec4 zwzy", "testbvec4a::2, testbvec4a::3, testbvec4a::2, testbvec4a::1", "testbvec4a.zwzy")
    Test("BVec4 zwzx", "testbvec4a::2, testbvec4a::3, testbvec4a::2, testbvec4a::0", "testbvec4a.zwzx")
    Test("BVec4 zwzw", "testbvec4a::2, testbvec4a::3, testbvec4a::2, testbvec4a::3", "testbvec4a.zwzw")
    Test("BVec4 zwzz", "testbvec4a::2, testbvec4a::3, testbvec4a::2, testbvec4a::2", "testbvec4a.zwzz")
    Test("BVec4 zwwy", "testbvec4a::2, testbvec4a::3, testbvec4a::3, testbvec4a::1", "testbvec4a.zwwy")
    Test("BVec4 zwwx", "testbvec4a::2, testbvec4a::3, testbvec4a::3, testbvec4a::0", "testbvec4a.zwwx")
    Test("BVec4 zwww", "testbvec4a::2, testbvec4a::3, testbvec4a::3, testbvec4a::3", "testbvec4a.zwww")
    Test("BVec4 zwwz", "testbvec4a::2, testbvec4a::3, testbvec4a::3, testbvec4a::2", "testbvec4a.zwwz")
    Test("BVec4 wxxx", "testbvec4a::3, testbvec4a::0, testbvec4a::0, testbvec4a::0", "testbvec4a.wxxx")
    Test("BVec4 wxxy", "testbvec4a::3, testbvec4a::0, testbvec4a::0, testbvec4a::1", "testbvec4a.wxxy")
    Test("BVec4 wxxz", "testbvec4a::3, testbvec4a::0, testbvec4a::0, testbvec4a::2", "testbvec4a.wxxz")
    Test("BVec4 wxxw", "testbvec4a::3, testbvec4a::0, testbvec4a::0, testbvec4a::3", "testbvec4a.wxxw")
    Test("BVec4 wxyx", "testbvec4a::3, testbvec4a::0, testbvec4a::1, testbvec4a::0", "testbvec4a.wxyx")
    Test("BVec4 wxyy", "testbvec4a::3, testbvec4a::0, testbvec4a::1, testbvec4a::1", "testbvec4a.wxyy")
    Test("BVec4 wxyz", "testbvec4a::3, testbvec4a::0, testbvec4a::1, testbvec4a::2", "testbvec4a.wxyz")
    Test("BVec4 wxyw", "testbvec4a::3, testbvec4a::0, testbvec4a::1, testbvec4a::3", "testbvec4a.wxyw")
    Test("BVec4 wxzx", "testbvec4a::3, testbvec4a::0, testbvec4a::2, testbvec4a::0", "testbvec4a.wxzx")
    Test("BVec4 wxzy", "testbvec4a::3, testbvec4a::0, testbvec4a::2, testbvec4a::1", "testbvec4a.wxzy")
    Test("BVec4 wxzz", "testbvec4a::3, testbvec4a::0, testbvec4a::2, testbvec4a::2", "testbvec4a.wxzz")
    Test("BVec4 wxzw", "testbvec4a::3, testbvec4a::0, testbvec4a::2, testbvec4a::3", "testbvec4a.wxzw")
    Test("BVec4 wxwx", "testbvec4a::3, testbvec4a::0, testbvec4a::3, testbvec4a::0", "testbvec4a.wxwx")
    Test("BVec4 wxwy", "testbvec4a::3, testbvec4a::0, testbvec4a::3, testbvec4a::1", "testbvec4a.wxwy")
    Test("BVec4 wxwz", "testbvec4a::3, testbvec4a::0, testbvec4a::3, testbvec4a::2", "testbvec4a.wxwz")
    Test("BVec4 wxww", "testbvec4a::3, testbvec4a::0, testbvec4a::3, testbvec4a::3", "testbvec4a.wxww")
    Test("BVec4 wyxx", "testbvec4a::3, testbvec4a::1, testbvec4a::0, testbvec4a::0", "testbvec4a.wyxx")
    Test("BVec4 wyxy", "testbvec4a::3, testbvec4a::1, testbvec4a::0, testbvec4a::1", "testbvec4a.wyxy")
    Test("BVec4 wyxz", "testbvec4a::3, testbvec4a::1, testbvec4a::0, testbvec4a::2", "testbvec4a.wyxz")
    Test("BVec4 wyxw", "testbvec4a::3, testbvec4a::1, testbvec4a::0, testbvec4a::3", "testbvec4a.wyxw")
    Test("BVec4 wyyx", "testbvec4a::3, testbvec4a::1, testbvec4a::1, testbvec4a::0", "testbvec4a.wyyx")
    Test("BVec4 wyyy", "testbvec4a::3, testbvec4a::1, testbvec4a::1, testbvec4a::1", "testbvec4a.wyyy")
    Test("BVec4 wyyz", "testbvec4a::3, testbvec4a::1, testbvec4a::1, testbvec4a::2", "testbvec4a.wyyz")
    Test("BVec4 wyyw", "testbvec4a::3, testbvec4a::1, testbvec4a::1, testbvec4a::3", "testbvec4a.wyyw")
    Test("BVec4 wyzx", "testbvec4a::3, testbvec4a::1, testbvec4a::2, testbvec4a::0", "testbvec4a.wyzx")
    Test("BVec4 wyzy", "testbvec4a::3, testbvec4a::1, testbvec4a::2, testbvec4a::1", "testbvec4a.wyzy")
    Test("BVec4 wyzz", "testbvec4a::3, testbvec4a::1, testbvec4a::2, testbvec4a::2", "testbvec4a.wyzz")
    Test("BVec4 wyzw", "testbvec4a::3, testbvec4a::1, testbvec4a::2, testbvec4a::3", "testbvec4a.wyzw")
    Test("BVec4 wywy", "testbvec4a::3, testbvec4a::1, testbvec4a::3, testbvec4a::1", "testbvec4a.wywy")
    Test("BVec4 wywx", "testbvec4a::3, testbvec4a::1, testbvec4a::3, testbvec4a::0", "testbvec4a.wywx")
    Test("BVec4 wyww", "testbvec4a::3, testbvec4a::1, testbvec4a::3, testbvec4a::3", "testbvec4a.wyww")
    Test("BVec4 wywz", "testbvec4a::3, testbvec4a::1, testbvec4a::3, testbvec4a::2", "testbvec4a.wywz")
    Test("BVec4 wzxy", "testbvec4a::3, testbvec4a::2, testbvec4a::0, testbvec4a::1", "testbvec4a.wzxy")
    Test("BVec4 wzxx", "testbvec4a::3, testbvec4a::2, testbvec4a::0, testbvec4a::0", "testbvec4a.wzxx")
    Test("BVec4 wzxw", "testbvec4a::3, testbvec4a::2, testbvec4a::0, testbvec4a::3", "testbvec4a.wzxw")
    Test("BVec4 wzxz", "testbvec4a::3, testbvec4a::2, testbvec4a::0, testbvec4a::2", "testbvec4a.wzxz")
    Test("BVec4 wzyy", "testbvec4a::3, testbvec4a::2, testbvec4a::1, testbvec4a::1", "testbvec4a.wzyy")
    Test("BVec4 wzyx", "testbvec4a::3, testbvec4a::2, testbvec4a::1, testbvec4a::0", "testbvec4a.wzyx")
    Test("BVec4 wzyw", "testbvec4a::3, testbvec4a::2, testbvec4a::1, testbvec4a::3", "testbvec4a.wzyw")
    Test("BVec4 wzyz", "testbvec4a::3, testbvec4a::2, testbvec4a::1, testbvec4a::2", "testbvec4a.wzyz")
    Test("BVec4 wzzy", "testbvec4a::3, testbvec4a::2, testbvec4a::2, testbvec4a::1", "testbvec4a.wzzy")
    Test("BVec4 wzzx", "testbvec4a::3, testbvec4a::2, testbvec4a::2, testbvec4a::0", "testbvec4a.wzzx")
    Test("BVec4 wzzw", "testbvec4a::3, testbvec4a::2, testbvec4a::2, testbvec4a::3", "testbvec4a.wzzw")
    Test("BVec4 wzzz", "testbvec4a::3, testbvec4a::2, testbvec4a::2, testbvec4a::2", "testbvec4a.wzzz")
    Test("BVec4 wzwy", "testbvec4a::3, testbvec4a::2, testbvec4a::3, testbvec4a::1", "testbvec4a.wzwy")
    Test("BVec4 wzwx", "testbvec4a::3, testbvec4a::2, testbvec4a::3, testbvec4a::0", "testbvec4a.wzwx")
    Test("BVec4 wzww", "testbvec4a::3, testbvec4a::2, testbvec4a::3, testbvec4a::3", "testbvec4a.wzww")
    Test("BVec4 wzwz", "testbvec4a::3, testbvec4a::2, testbvec4a::3, testbvec4a::2", "testbvec4a.wzwz")
    Test("BVec4 wwxy", "testbvec4a::3, testbvec4a::3, testbvec4a::0, testbvec4a::1", "testbvec4a.wwxy")
    Test("BVec4 wwxx", "testbvec4a::3, testbvec4a::3, testbvec4a::0, testbvec4a::0", "testbvec4a.wwxx")
    Test("BVec4 wwxw", "testbvec4a::3, testbvec4a::3, testbvec4a::0, testbvec4a::3", "testbvec4a.wwxw")
    Test("BVec4 wwxz", "testbvec4a::3, testbvec4a::3, testbvec4a::0, testbvec4a::2", "testbvec4a.wwxz")
    Test("BVec4 wwyy", "testbvec4a::3, testbvec4a::3, testbvec4a::1, testbvec4a::1", "testbvec4a.wwyy")
    Test("BVec4 wwyx", "testbvec4a::3, testbvec4a::3, testbvec4a::1, testbvec4a::0", "testbvec4a.wwyx")
    Test("BVec4 wwyw", "testbvec4a::3, testbvec4a::3, testbvec4a::1, testbvec4a::3", "testbvec4a.wwyw")
    Test("BVec4 wwyz", "testbvec4a::3, testbvec4a::3, testbvec4a::1, testbvec4a::2", "testbvec4a.wwyz")
    Test("BVec4 wwzy", "testbvec4a::3, testbvec4a::3, testbvec4a::2, testbvec4a::1", "testbvec4a.wwzy")
    Test("BVec4 wwzx", "testbvec4a::3, testbvec4a::3, testbvec4a::2, testbvec4a::0", "testbvec4a.wwzx")
    Test("BVec4 wwzw", "testbvec4a::3, testbvec4a::3, testbvec4a::2, testbvec4a::3", "testbvec4a.wwzw")
    Test("BVec4 wwzz", "testbvec4a::3, testbvec4a::3, testbvec4a::2, testbvec4a::2", "testbvec4a.wwzz")
    Test("BVec4 wwwy", "testbvec4a::3, testbvec4a::3, testbvec4a::3, testbvec4a::1", "testbvec4a.wwwy")
    Test("BVec4 wwwx", "testbvec4a::3, testbvec4a::3, testbvec4a::3, testbvec4a::0", "testbvec4a.wwwx")
    Test("BVec4 wwww", "testbvec4a::3, testbvec4a::3, testbvec4a::3, testbvec4a::3", "testbvec4a.wwww")
    Test("BVec4 wwwz", "testbvec4a::3, testbvec4a::3, testbvec4a::3, testbvec4a::2", "testbvec4a.wwwz")
    Test("BVec4 ab", "testbvec4a::1, testbvec4b::1", "bvec2(testbvec4a.y, testbvec4b.y)")
    Test("BVec4 aba", "testbvec4a::1, testbvec4b::1, testbvec4a::1", "bvec3(testbvec4a.y, testbvec4b.y, testbvec4a.y)")
    Test("BVec4 baa", "testbvec4b::1, testbvec4a::1, testbvec4a::1", "bvec3(testbvec4b.y, testbvec4a.y, testbvec4a.y)")
    Test("BVec4 aab", "testbvec4a::1, testbvec4a::1, testbvec4b::1", "bvec3(testbvec4a.y, testbvec4a.y, testbvec4b.y)")
    Test("BVec4 baaa", "testbvec4b::1, testbvec4a::1, testbvec4a::1, testbvec4a::1", "bvec4(testbvec4b.y, testbvec4a.y, testbvec4a.y, testbvec4a.y)")
    Test("BVec4 abaa", "testbvec4a::1, testbvec4b::1, testbvec4a::1, testbvec4a::1", "bvec4(testbvec4a.y, testbvec4b.y, testbvec4a.y, testbvec4a.y)")
    Test("BVec4 aaba", "testbvec4a::1, testbvec4a::1, testbvec4b::1, testbvec4a::1", "bvec4(testbvec4a.y, testbvec4a.y, testbvec4b.y, testbvec4a.y)")
    Test("BVec4 aaab", "testbvec4a::1, testbvec4a::1, testbvec4a::1, testbvec4b::1", "bvec4(testbvec4a.y, testbvec4a.y, testbvec4a.y, testbvec4b.y)")
    Test("BVec4 aabb", "testbvec4a::1, testbvec4a::1, testbvec4b::1, testbvec4b::1", "bvec4(testbvec4a.y, testbvec4a.y, testbvec4b.y, testbvec4b.y)")
    Test("BVec4 abba", "testbvec4a::1, testbvec4b::1, testbvec4b::1, testbvec4a::1", "bvec4(testbvec4a.y, testbvec4b.y, testbvec4b.y, testbvec4a.y)")
    Test("BVec4 5 components", "testbvec4a::3, testbvec4a::3, testbvec4a::3, testbvec4a::2, testbvec4a::3", undefined)

    Test("BVec3 x", "testbvec3a::0", "testbvec3a.x")
    Test("BVec3 y", "testbvec3a::1", "testbvec3a.y")
    Test("BVec3 z", "testbvec3a::2", "testbvec3a.z")
    Test("BVec3 xx", "testbvec3a::0, testbvec3a::0", "testbvec3a.xx")
    Test("BVec3 xy", "testbvec3a::0, testbvec3a::1", "testbvec3a.xy")
    Test("BVec3 xz", "testbvec3a::0, testbvec3a::2", "testbvec3a.xz")
    Test("BVec3 yx", "testbvec3a::1, testbvec3a::0", "testbvec3a.yx")
    Test("BVec3 yy", "testbvec3a::1, testbvec3a::1", "testbvec3a.yy")
    Test("BVec3 yz", "testbvec3a::1, testbvec3a::2", "testbvec3a.yz")
    Test("BVec3 zx", "testbvec3a::2, testbvec3a::0", "testbvec3a.zx")
    Test("BVec3 zy", "testbvec3a::2, testbvec3a::1", "testbvec3a.zy")
    Test("BVec3 zz", "testbvec3a::2, testbvec3a::2", "testbvec3a.zz")
    Test("BVec3 xxx", "testbvec3a::0, testbvec3a::0, testbvec3a::0", "testbvec3a.xxx")
    Test("BVec3 xxy", "testbvec3a::0, testbvec3a::0, testbvec3a::1", "testbvec3a.xxy")
    Test("BVec3 xxz", "testbvec3a::0, testbvec3a::0, testbvec3a::2", "testbvec3a.xxz")
    Test("BVec3 xyx", "testbvec3a::0, testbvec3a::1, testbvec3a::0", "testbvec3a.xyx")
    Test("BVec3 xyy", "testbvec3a::0, testbvec3a::1, testbvec3a::1", "testbvec3a.xyy")
    Test("BVec3 xyz", "testbvec3a::0, testbvec3a::1, testbvec3a::2", "testbvec3a")
    Test("BVec3 xzx", "testbvec3a::0, testbvec3a::2, testbvec3a::0", "testbvec3a.xzx")
    Test("BVec3 xzy", "testbvec3a::0, testbvec3a::2, testbvec3a::1", "testbvec3a.xzy")
    Test("BVec3 xzz", "testbvec3a::0, testbvec3a::2, testbvec3a::2", "testbvec3a.xzz")
    Test("BVec3 yxx", "testbvec3a::1, testbvec3a::0, testbvec3a::0", "testbvec3a.yxx")
    Test("BVec3 yxy", "testbvec3a::1, testbvec3a::0, testbvec3a::1", "testbvec3a.yxy")
    Test("BVec3 yxz", "testbvec3a::1, testbvec3a::0, testbvec3a::2", "testbvec3a.yxz")
    Test("BVec3 yyx", "testbvec3a::1, testbvec3a::1, testbvec3a::0", "testbvec3a.yyx")
    Test("BVec3 yyy", "testbvec3a::1, testbvec3a::1, testbvec3a::1", "testbvec3a.yyy")
    Test("BVec3 yyz", "testbvec3a::1, testbvec3a::1, testbvec3a::2", "testbvec3a.yyz")
    Test("BVec3 yzx", "testbvec3a::1, testbvec3a::2, testbvec3a::0", "testbvec3a.yzx")
    Test("BVec3 yzy", "testbvec3a::1, testbvec3a::2, testbvec3a::1", "testbvec3a.yzy")
    Test("BVec3 yzz", "testbvec3a::1, testbvec3a::2, testbvec3a::2", "testbvec3a.yzz")
    Test("BVec3 zxx", "testbvec3a::2, testbvec3a::0, testbvec3a::0", "testbvec3a.zxx")
    Test("BVec3 zxy", "testbvec3a::2, testbvec3a::0, testbvec3a::1", "testbvec3a.zxy")
    Test("BVec3 zxz", "testbvec3a::2, testbvec3a::0, testbvec3a::2", "testbvec3a.zxz")
    Test("BVec3 zyx", "testbvec3a::2, testbvec3a::1, testbvec3a::0", "testbvec3a.zyx")
    Test("BVec3 zyy", "testbvec3a::2, testbvec3a::1, testbvec3a::1", "testbvec3a.zyy")
    Test("BVec3 zyz", "testbvec3a::2, testbvec3a::1, testbvec3a::2", "testbvec3a.zyz")
    Test("BVec3 zzx", "testbvec3a::2, testbvec3a::2, testbvec3a::0", "testbvec3a.zzx")
    Test("BVec3 zzy", "testbvec3a::2, testbvec3a::2, testbvec3a::1", "testbvec3a.zzy")
    Test("BVec3 zzz", "testbvec3a::2, testbvec3a::2, testbvec3a::2", "testbvec3a.zzz")
    Test("BVec3 xxxx", "testbvec3a::0, testbvec3a::0, testbvec3a::0, testbvec3a::0", "testbvec3a.xxxx")
    Test("BVec3 xxxy", "testbvec3a::0, testbvec3a::0, testbvec3a::0, testbvec3a::1", "testbvec3a.xxxy")
    Test("BVec3 xxxz", "testbvec3a::0, testbvec3a::0, testbvec3a::0, testbvec3a::2", "testbvec3a.xxxz")
    Test("BVec3 xxyx", "testbvec3a::0, testbvec3a::0, testbvec3a::1, testbvec3a::0", "testbvec3a.xxyx")
    Test("BVec3 xxyy", "testbvec3a::0, testbvec3a::0, testbvec3a::1, testbvec3a::1", "testbvec3a.xxyy")
    Test("BVec3 xxyz", "testbvec3a::0, testbvec3a::0, testbvec3a::1, testbvec3a::2", "testbvec3a.xxyz")
    Test("BVec3 xxzx", "testbvec3a::0, testbvec3a::0, testbvec3a::2, testbvec3a::0", "testbvec3a.xxzx")
    Test("BVec3 xxzy", "testbvec3a::0, testbvec3a::0, testbvec3a::2, testbvec3a::1", "testbvec3a.xxzy")
    Test("BVec3 xxzz", "testbvec3a::0, testbvec3a::0, testbvec3a::2, testbvec3a::2", "testbvec3a.xxzz")
    Test("BVec3 xyxx", "testbvec3a::0, testbvec3a::1, testbvec3a::0, testbvec3a::0", "testbvec3a.xyxx")
    Test("BVec3 xyxy", "testbvec3a::0, testbvec3a::1, testbvec3a::0, testbvec3a::1", "testbvec3a.xyxy")
    Test("BVec3 xyxz", "testbvec3a::0, testbvec3a::1, testbvec3a::0, testbvec3a::2", "testbvec3a.xyxz")
    Test("BVec3 xyyx", "testbvec3a::0, testbvec3a::1, testbvec3a::1, testbvec3a::0", "testbvec3a.xyyx")
    Test("BVec3 xyyy", "testbvec3a::0, testbvec3a::1, testbvec3a::1, testbvec3a::1", "testbvec3a.xyyy")
    Test("BVec3 xyyz", "testbvec3a::0, testbvec3a::1, testbvec3a::1, testbvec3a::2", "testbvec3a.xyyz")
    Test("BVec3 xyzx", "testbvec3a::0, testbvec3a::1, testbvec3a::2, testbvec3a::0", "testbvec3a.xyzx")
    Test("BVec3 xyzy", "testbvec3a::0, testbvec3a::1, testbvec3a::2, testbvec3a::1", "testbvec3a.xyzy")
    Test("BVec3 xyzz", "testbvec3a::0, testbvec3a::1, testbvec3a::2, testbvec3a::2", "testbvec3a.xyzz")
    Test("BVec3 xzxx", "testbvec3a::0, testbvec3a::2, testbvec3a::0, testbvec3a::0", "testbvec3a.xzxx")
    Test("BVec3 xzxy", "testbvec3a::0, testbvec3a::2, testbvec3a::0, testbvec3a::1", "testbvec3a.xzxy")
    Test("BVec3 xzxz", "testbvec3a::0, testbvec3a::2, testbvec3a::0, testbvec3a::2", "testbvec3a.xzxz")
    Test("BVec3 xzyx", "testbvec3a::0, testbvec3a::2, testbvec3a::1, testbvec3a::0", "testbvec3a.xzyx")
    Test("BVec3 xzyy", "testbvec3a::0, testbvec3a::2, testbvec3a::1, testbvec3a::1", "testbvec3a.xzyy")
    Test("BVec3 xzyz", "testbvec3a::0, testbvec3a::2, testbvec3a::1, testbvec3a::2", "testbvec3a.xzyz")
    Test("BVec3 xzzx", "testbvec3a::0, testbvec3a::2, testbvec3a::2, testbvec3a::0", "testbvec3a.xzzx")
    Test("BVec3 xzzy", "testbvec3a::0, testbvec3a::2, testbvec3a::2, testbvec3a::1", "testbvec3a.xzzy")
    Test("BVec3 xzzz", "testbvec3a::0, testbvec3a::2, testbvec3a::2, testbvec3a::2", "testbvec3a.xzzz")
    Test("BVec3 yxxy", "testbvec3a::1, testbvec3a::0, testbvec3a::0, testbvec3a::1", "testbvec3a.yxxy")
    Test("BVec3 yxxx", "testbvec3a::1, testbvec3a::0, testbvec3a::0, testbvec3a::0", "testbvec3a.yxxx")
    Test("BVec3 yxxz", "testbvec3a::1, testbvec3a::0, testbvec3a::0, testbvec3a::2", "testbvec3a.yxxz")
    Test("BVec3 yxyx", "testbvec3a::1, testbvec3a::0, testbvec3a::1, testbvec3a::0", "testbvec3a.yxyx")
    Test("BVec3 yxyy", "testbvec3a::1, testbvec3a::0, testbvec3a::1, testbvec3a::1", "testbvec3a.yxyy")
    Test("BVec3 yxyz", "testbvec3a::1, testbvec3a::0, testbvec3a::1, testbvec3a::2", "testbvec3a.yxyz")
    Test("BVec3 yxzx", "testbvec3a::1, testbvec3a::0, testbvec3a::2, testbvec3a::0", "testbvec3a.yxzx")
    Test("BVec3 yxzy", "testbvec3a::1, testbvec3a::0, testbvec3a::2, testbvec3a::1", "testbvec3a.yxzy")
    Test("BVec3 yxzz", "testbvec3a::1, testbvec3a::0, testbvec3a::2, testbvec3a::2", "testbvec3a.yxzz")
    Test("BVec3 yyxx", "testbvec3a::1, testbvec3a::1, testbvec3a::0, testbvec3a::0", "testbvec3a.yyxx")
    Test("BVec3 yyxy", "testbvec3a::1, testbvec3a::1, testbvec3a::0, testbvec3a::1", "testbvec3a.yyxy")
    Test("BVec3 yyxz", "testbvec3a::1, testbvec3a::1, testbvec3a::0, testbvec3a::2", "testbvec3a.yyxz")
    Test("BVec3 yyyx", "testbvec3a::1, testbvec3a::1, testbvec3a::1, testbvec3a::0", "testbvec3a.yyyx")
    Test("BVec3 yyyy", "testbvec3a::1, testbvec3a::1, testbvec3a::1, testbvec3a::1", "testbvec3a.yyyy")
    Test("BVec3 yyyz", "testbvec3a::1, testbvec3a::1, testbvec3a::1, testbvec3a::2", "testbvec3a.yyyz")
    Test("BVec3 yyzx", "testbvec3a::1, testbvec3a::1, testbvec3a::2, testbvec3a::0", "testbvec3a.yyzx")
    Test("BVec3 yyzy", "testbvec3a::1, testbvec3a::1, testbvec3a::2, testbvec3a::1", "testbvec3a.yyzy")
    Test("BVec3 yyzz", "testbvec3a::1, testbvec3a::1, testbvec3a::2, testbvec3a::2", "testbvec3a.yyzz")
    Test("BVec3 yzxx", "testbvec3a::1, testbvec3a::2, testbvec3a::0, testbvec3a::0", "testbvec3a.yzxx")
    Test("BVec3 yzxy", "testbvec3a::1, testbvec3a::2, testbvec3a::0, testbvec3a::1", "testbvec3a.yzxy")
    Test("BVec3 yzxz", "testbvec3a::1, testbvec3a::2, testbvec3a::0, testbvec3a::2", "testbvec3a.yzxz")
    Test("BVec3 yzyx", "testbvec3a::1, testbvec3a::2, testbvec3a::1, testbvec3a::0", "testbvec3a.yzyx")
    Test("BVec3 yzyy", "testbvec3a::1, testbvec3a::2, testbvec3a::1, testbvec3a::1", "testbvec3a.yzyy")
    Test("BVec3 yzyz", "testbvec3a::1, testbvec3a::2, testbvec3a::1, testbvec3a::2", "testbvec3a.yzyz")
    Test("BVec3 yzzx", "testbvec3a::1, testbvec3a::2, testbvec3a::2, testbvec3a::0", "testbvec3a.yzzx")
    Test("BVec3 yzzy", "testbvec3a::1, testbvec3a::2, testbvec3a::2, testbvec3a::1", "testbvec3a.yzzy")
    Test("BVec3 yzzz", "testbvec3a::1, testbvec3a::2, testbvec3a::2, testbvec3a::2", "testbvec3a.yzzz")
    Test("BVec3 zxxy", "testbvec3a::2, testbvec3a::0, testbvec3a::0, testbvec3a::1", "testbvec3a.zxxy")
    Test("BVec3 zxxx", "testbvec3a::2, testbvec3a::0, testbvec3a::0, testbvec3a::0", "testbvec3a.zxxx")
    Test("BVec3 zxxz", "testbvec3a::2, testbvec3a::0, testbvec3a::0, testbvec3a::2", "testbvec3a.zxxz")
    Test("BVec3 zxyx", "testbvec3a::2, testbvec3a::0, testbvec3a::1, testbvec3a::0", "testbvec3a.zxyx")
    Test("BVec3 zxyy", "testbvec3a::2, testbvec3a::0, testbvec3a::1, testbvec3a::1", "testbvec3a.zxyy")
    Test("BVec3 zxyz", "testbvec3a::2, testbvec3a::0, testbvec3a::1, testbvec3a::2", "testbvec3a.zxyz")
    Test("BVec3 zxzx", "testbvec3a::2, testbvec3a::0, testbvec3a::2, testbvec3a::0", "testbvec3a.zxzx")
    Test("BVec3 zxzy", "testbvec3a::2, testbvec3a::0, testbvec3a::2, testbvec3a::1", "testbvec3a.zxzy")
    Test("BVec3 zxzz", "testbvec3a::2, testbvec3a::0, testbvec3a::2, testbvec3a::2", "testbvec3a.zxzz")
    Test("BVec3 zyxx", "testbvec3a::2, testbvec3a::1, testbvec3a::0, testbvec3a::0", "testbvec3a.zyxx")
    Test("BVec3 zyxy", "testbvec3a::2, testbvec3a::1, testbvec3a::0, testbvec3a::1", "testbvec3a.zyxy")
    Test("BVec3 zyxz", "testbvec3a::2, testbvec3a::1, testbvec3a::0, testbvec3a::2", "testbvec3a.zyxz")
    Test("BVec3 zyyx", "testbvec3a::2, testbvec3a::1, testbvec3a::1, testbvec3a::0", "testbvec3a.zyyx")
    Test("BVec3 zyyy", "testbvec3a::2, testbvec3a::1, testbvec3a::1, testbvec3a::1", "testbvec3a.zyyy")
    Test("BVec3 zyyz", "testbvec3a::2, testbvec3a::1, testbvec3a::1, testbvec3a::2", "testbvec3a.zyyz")
    Test("BVec3 zyzx", "testbvec3a::2, testbvec3a::1, testbvec3a::2, testbvec3a::0", "testbvec3a.zyzx")
    Test("BVec3 zyzy", "testbvec3a::2, testbvec3a::1, testbvec3a::2, testbvec3a::1", "testbvec3a.zyzy")
    Test("BVec3 zyzz", "testbvec3a::2, testbvec3a::1, testbvec3a::2, testbvec3a::2", "testbvec3a.zyzz")
    Test("BVec3 zzxx", "testbvec3a::2, testbvec3a::2, testbvec3a::0, testbvec3a::0", "testbvec3a.zzxx")
    Test("BVec3 zzxy", "testbvec3a::2, testbvec3a::2, testbvec3a::0, testbvec3a::1", "testbvec3a.zzxy")
    Test("BVec3 zzxz", "testbvec3a::2, testbvec3a::2, testbvec3a::0, testbvec3a::2", "testbvec3a.zzxz")
    Test("BVec3 zzyx", "testbvec3a::2, testbvec3a::2, testbvec3a::1, testbvec3a::0", "testbvec3a.zzyx")
    Test("BVec3 zzyy", "testbvec3a::2, testbvec3a::2, testbvec3a::1, testbvec3a::1", "testbvec3a.zzyy")
    Test("BVec3 zzyz", "testbvec3a::2, testbvec3a::2, testbvec3a::1, testbvec3a::2", "testbvec3a.zzyz")
    Test("BVec3 zzzx", "testbvec3a::2, testbvec3a::2, testbvec3a::2, testbvec3a::0", "testbvec3a.zzzx")
    Test("BVec3 zzzy", "testbvec3a::2, testbvec3a::2, testbvec3a::2, testbvec3a::1", "testbvec3a.zzzy")
    Test("BVec3 zzzz", "testbvec3a::2, testbvec3a::2, testbvec3a::2, testbvec3a::2", "testbvec3a.zzzz")
    Test("BVec3 ab", "testbvec3a::1, testbvec3b::1", "bvec2(testbvec3a.y, testbvec3b.y)")
    Test("BVec3 aba", "testbvec3a::1, testbvec3b::1, testbvec3a::1", "bvec3(testbvec3a.y, testbvec3b.y, testbvec3a.y)")
    Test("BVec3 baa", "testbvec3b::1, testbvec3a::1, testbvec3a::1", "bvec3(testbvec3b.y, testbvec3a.y, testbvec3a.y)")
    Test("BVec3 aab", "testbvec3a::1, testbvec3a::1, testbvec3b::1", "bvec3(testbvec3a.y, testbvec3a.y, testbvec3b.y)")
    Test("BVec3 baaa", "testbvec3b::1, testbvec3a::1, testbvec3a::1, testbvec3a::1", "bvec4(testbvec3b.y, testbvec3a.y, testbvec3a.y, testbvec3a.y)")
    Test("BVec3 abaa", "testbvec3a::1, testbvec3b::1, testbvec3a::1, testbvec3a::1", "bvec4(testbvec3a.y, testbvec3b.y, testbvec3a.y, testbvec3a.y)")
    Test("BVec3 aaba", "testbvec3a::1, testbvec3a::1, testbvec3b::1, testbvec3a::1", "bvec4(testbvec3a.y, testbvec3a.y, testbvec3b.y, testbvec3a.y)")
    Test("BVec3 aaab", "testbvec3a::1, testbvec3a::1, testbvec3a::1, testbvec3b::1", "bvec4(testbvec3a.y, testbvec3a.y, testbvec3a.y, testbvec3b.y)")
    Test("BVec3 aabb", "testbvec3a::1, testbvec3a::1, testbvec3b::1, testbvec3b::1", "bvec4(testbvec3a.y, testbvec3a.y, testbvec3b.y, testbvec3b.y)")
    Test("BVec3 abba", "testbvec3a::1, testbvec3b::1, testbvec3b::1, testbvec3a::1", "bvec4(testbvec3a.y, testbvec3b.y, testbvec3b.y, testbvec3a.y)")
    Test("BVec3 5 components", "testbvec3a::2, testbvec3a::2, testbvec3a::2, testbvec3a::2, testbvec3a: 1", undefined)

    Test("BVec2 x", "testbvec2a::0", "testbvec2a.x")
    Test("BVec2 y", "testbvec2a::1", "testbvec2a.y")
    Test("BVec2 xx", "testbvec2a::0, testbvec2a::0", "testbvec2a.xx")
    Test("BVec2 xy", "testbvec2a::0, testbvec2a::1", "testbvec2a")
    Test("BVec2 yx", "testbvec2a::1, testbvec2a::0", "testbvec2a.yx")
    Test("BVec2 yy", "testbvec2a::1, testbvec2a::1", "testbvec2a.yy")
    Test("BVec2 xxx", "testbvec2a::0, testbvec2a::0, testbvec2a::0", "testbvec2a.xxx")
    Test("BVec2 xxy", "testbvec2a::0, testbvec2a::0, testbvec2a::1", "testbvec2a.xxy")
    Test("BVec2 xyx", "testbvec2a::0, testbvec2a::1, testbvec2a::0", "testbvec2a.xyx")
    Test("BVec2 xyy", "testbvec2a::0, testbvec2a::1, testbvec2a::1", "testbvec2a.xyy")
    Test("BVec2 yxx", "testbvec2a::1, testbvec2a::0, testbvec2a::0", "testbvec2a.yxx")
    Test("BVec2 yxy", "testbvec2a::1, testbvec2a::0, testbvec2a::1", "testbvec2a.yxy")
    Test("BVec2 yyx", "testbvec2a::1, testbvec2a::1, testbvec2a::0", "testbvec2a.yyx")
    Test("BVec2 yyy", "testbvec2a::1, testbvec2a::1, testbvec2a::1", "testbvec2a.yyy")
    Test("BVec2 xxxx", "testbvec2a::0, testbvec2a::0, testbvec2a::0, testbvec2a::0", "testbvec2a.xxxx")
    Test("BVec2 xxxy", "testbvec2a::0, testbvec2a::0, testbvec2a::0, testbvec2a::1", "testbvec2a.xxxy")
    Test("BVec2 xxyx", "testbvec2a::0, testbvec2a::0, testbvec2a::1, testbvec2a::0", "testbvec2a.xxyx")
    Test("BVec2 xxyy", "testbvec2a::0, testbvec2a::0, testbvec2a::1, testbvec2a::1", "testbvec2a.xxyy")
    Test("BVec2 xyxx", "testbvec2a::0, testbvec2a::1, testbvec2a::0, testbvec2a::0", "testbvec2a.xyxx")
    Test("BVec2 xyxy", "testbvec2a::0, testbvec2a::1, testbvec2a::0, testbvec2a::1", "testbvec2a.xyxy")
    Test("BVec2 xyyx", "testbvec2a::0, testbvec2a::1, testbvec2a::1, testbvec2a::0", "testbvec2a.xyyx")
    Test("BVec2 xyyy", "testbvec2a::0, testbvec2a::1, testbvec2a::1, testbvec2a::1", "testbvec2a.xyyy")
    Test("BVec2 yxxx", "testbvec2a::1, testbvec2a::0, testbvec2a::0, testbvec2a::0", "testbvec2a.yxxx")
    Test("BVec2 yxxy", "testbvec2a::1, testbvec2a::0, testbvec2a::0, testbvec2a::1", "testbvec2a.yxxy")
    Test("BVec2 yxyx", "testbvec2a::1, testbvec2a::0, testbvec2a::1, testbvec2a::0", "testbvec2a.yxyx")
    Test("BVec2 yxyy", "testbvec2a::1, testbvec2a::0, testbvec2a::1, testbvec2a::1", "testbvec2a.yxyy")
    Test("BVec2 yyxx", "testbvec2a::1, testbvec2a::1, testbvec2a::0, testbvec2a::0", "testbvec2a.yyxx")
    Test("BVec2 yyxy", "testbvec2a::1, testbvec2a::1, testbvec2a::0, testbvec2a::1", "testbvec2a.yyxy")
    Test("BVec2 yyyx", "testbvec2a::1, testbvec2a::1, testbvec2a::1, testbvec2a::0", "testbvec2a.yyyx")
    Test("BVec2 yyyy", "testbvec2a::1, testbvec2a::1, testbvec2a::1, testbvec2a::1", "testbvec2a.yyyy")
    Test("BVec2 ab", "testbvec2a::1, testbvec2b::1", "bvec2(testbvec2a.y, testbvec2b.y)")
    Test("BVec2 aba", "testbvec2a::1, testbvec2b::1, testbvec2a::1", "bvec3(testbvec2a.y, testbvec2b.y, testbvec2a.y)")
    Test("BVec2 baa", "testbvec2b::1, testbvec2a::1, testbvec2a::1", "bvec3(testbvec2b.y, testbvec2a.y, testbvec2a.y)")
    Test("BVec2 aab", "testbvec2a::1, testbvec2a::1, testbvec2b::1", "bvec3(testbvec2a.y, testbvec2a.y, testbvec2b.y)")
    Test("BVec2 baaa", "testbvec2b::1, testbvec2a::1, testbvec2a::1, testbvec2a::1", "bvec4(testbvec2b.y, testbvec2a.y, testbvec2a.y, testbvec2a.y)")
    Test("BVec2 abaa", "testbvec2a::1, testbvec2b::1, testbvec2a::1, testbvec2a::1", "bvec4(testbvec2a.y, testbvec2b.y, testbvec2a.y, testbvec2a.y)")
    Test("BVec2 aaba", "testbvec2a::1, testbvec2a::1, testbvec2b::1, testbvec2a::1", "bvec4(testbvec2a.y, testbvec2a.y, testbvec2b.y, testbvec2a.y)")
    Test("BVec2 aaab", "testbvec2a::1, testbvec2a::1, testbvec2a::1, testbvec2b::1", "bvec4(testbvec2a.y, testbvec2a.y, testbvec2a.y, testbvec2b.y)")
    Test("BVec2 aabb", "testbvec2a::1, testbvec2a::1, testbvec2b::1, testbvec2b::1", "bvec4(testbvec2a.y, testbvec2a.y, testbvec2b.y, testbvec2b.y)")
    Test("BVec2 abba", "testbvec2a::1, testbvec2b::1, testbvec2b::1, testbvec2a::1", "bvec4(testbvec2a.y, testbvec2b.y, testbvec2b.y, testbvec2a.y)")
    Test("BVec2 5 components", "testbvec2a::1, testbvec2a::1, testbvec2a::1, testbvec2a::1, testbvec2a::0", undefined)
})